apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: myapp
    putty.sbw.io: "true"
spec:
  containers:
  - name: example-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes!']
